# Data Preprocessing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing Dataset

In [2]:
data_set = pd.read_csv('Data.csv')

In [3]:
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [4]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [5]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']


### Handling Missing Data

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')

In [7]:
imputer.fit(X[:, 0:1])
#print(X[:, 0:1])

X[:, 0:1] = imputer.transform(X[:, 0:1])
#print(X[:, 0:1])

In [12]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

In [10]:
imputer.fit(X[:, 4:5])
#print(X[:, 4:5])

X[:, 4:5] = imputer.transform(X[:, 4:5])
#print(X[:, 4:5])

In [13]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

## Encoding Categorical Data

### Encoding independent variables

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
print(X)

[[0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 12.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 15.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 12.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 15.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 18.0 'no' 'no' 66.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 17.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 16.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 25.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 24.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 30.0 'no' 'no' 62.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 89.0]
 [0.0 0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 0.0 1.0 26.0 'no' 'no' 82.07246376811594]
 [0.0 0.0 1.0 28.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 30.0 'yes' 'no' 86.0]
 [0.0 1.0 0.0 35.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 32.0 'no' 'yes' 84.0]
 [0.

In [17]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [4])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [18]:
print(X)

[[1.0 0.0 0.0 0.0 1.0 10.0 'no' 97.0]
 [1.0 0.0 0.0 0.0 1.0 12.0 'no' 97.0]
 [1.0 0.0 0.0 0.0 1.0 15.0 'no' 94.0]
 [1.0 0.0 0.0 0.0 1.0 10.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 0.0 13.0 'no' 94.0]
 [1.0 0.0 0.0 1.0 0.0 12.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 0.0 13.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 0.0 15.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 0.0 18.0 'no' 66.0]
 [1.0 0.0 0.0 0.0 1.0 19.0 'no' 92.0]
 [1.0 0.0 0.0 0.0 1.0 20.0 'no' 93.0]
 [1.0 0.0 0.0 0.0 1.0 17.0 'no' 93.0]
 [1.0 0.0 0.0 0.0 1.0 16.0 'no' 92.0]
 [1.0 0.0 0.0 0.0 1.0 18.0 'no' 93.0]
 [1.0 0.0 0.0 0.0 1.0 20.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 0.0 25.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 0.0 24.0 'no' 92.0]
 [1.0 0.0 1.0 0.0 0.0 26.0 'no' 94.0]
 [1.0 0.0 0.0 0.0 1.0 28.0 'no' 99.0]
 [1.0 0.0 0.0 0.0 1.0 29.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 0.0 30.0 'no' 62.0]
 [1.0 0.0 0.0 0.0 1.0 19.0 'no' 89.0]
 [1.0 0.0 0.0 0.0 1.0 25.0 'yes' 86.0]
 [1.0 0.0 0.0 0.0 1.0 26.0 'no' 82.07246376811594]
 [1.0 0.0 0.0 0.0 1.0 28.0 'no' 89.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 'no' 86.0

In [19]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [6])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 12.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 15.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 13.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 12.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 13.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 15.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 18.0 66.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 19.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 20.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 17.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 16.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 18.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 20.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 25.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 24.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 26.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 28.0 99.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 30.0 62.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 19.0 89.0]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 25.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 26.0 82.07246376811594]
 [1

### Encoding dependent variables

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [22]:
print(y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


## Splitting data into Test set & Training Set


In [23]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [24]:
print(X_train)

[[0.0 1.0 0.0 1.0 1.0 0.0 0.0 86.0 71.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 35.0 92.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 75.0 72.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 42.0 92.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 74.0 75.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 62.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 24.0 92.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 48.0 93.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 58.0 70.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 45.130434782608695 90.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 15.0 92.0]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 70.0 88.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 52.0 80.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 60.0 68.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 54.0 70.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 93.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 78.0 71.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 36.0 90.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 30.0 86.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 50.0 77.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 18.0 93.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 69.0 53.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 26.0 94.0]
 [

In [25]:
print(X_test)

[[0.0 1.0 1.0 0.0 0.0 0.0 1.0 25.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 68.0 67.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 13.0 94.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 59.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 28.0 99.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 20.0 93.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 46.0 91.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 53.0 55.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 16.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 38.0 75.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 19.0 92.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 94.0 64.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 12.0 97.0]]


In [26]:
print(y_train)

[1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1]


In [27]:
print(y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


## Feature Scaling

In [28]:
#Feature Scaling on Blood O2 Level in Percentage

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 6:] = sc.fit_transform(X_train[:, 6:])
X_test[:, 6:] = sc.fit_transform(X_test[:, 6:])

In [30]:
print(X_train)

[[0.0 1.0 0.0 1.0 1.0 0.0 -0.4944132324730441 1.6605950326521113
  -0.9941858494300264]
 [0.0 1.0 1.0 0.0 0.0 1.0 -0.4944132324730441 -0.5372483818439074
  0.957435414508189]
 [0.0 1.0 1.0 0.0 1.0 0.0 -0.4944132324730441 1.1865503746235584
  -0.9012515035282067]
 [1.0 0.0 1.0 0.0 1.0 0.0 -0.4944132324730441 -0.23558359946210097
  0.957435414508189]
 [0.0 1.0 0.0 1.0 1.0 0.0 -0.4944132324730441 1.1434554057118715
  -0.6224484658227473]
 [0.0 1.0 0.0 1.0 1.0 0.0 -0.4944132324730441 0.6263157787716319
  -1.2729888871354857]
 [1.0 0.0 1.0 0.0 0.0 1.0 -0.4944132324730441 -1.0112930398724607
  0.957435414508189]
 [0.0 1.0 1.0 0.0 0.0 1.0 -0.4944132324730441 0.022986214008018896
  1.0503697604100088]
 [1.0 0.0 1.0 0.0 1.0 0.0 -0.4944132324730441 0.45393590312488535
  -1.0871201953318463]
 [1.0 0.0 0.0 1.0 0.0 1.0 -0.4944132324730441 -0.10067760982551671
  0.7715667227045494]
 [1.0 0.0 1.0 0.0 0.0 1.0 -0.4944132324730441 -1.3991477600776403
  0.957435414508189]
 [0.0 1.0 1.0 0.0 0.0 0.0 2.0225

In [31]:
print(X_test)

[[0.0 1.0 1.0 0.0 0.0 0.0 1.1547005383792517 -0.4451102407099234
  0.17205102992570073]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.1547005383792517 -1.0641377277899493
  0.9513409890009328]
 [1.0 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387 1.3294352222528176
  -1.1739952630224273]
 [1.0 0.0 1.0 0.0 0.0 1.0 -0.8660254037844387 -0.9403322303739441
  0.7388073637985968]
 [1.0 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387 0.9580187300048021
  -1.1031507212883154]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.1547005383792517 -0.32130474329391817
  1.0930300724691568]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.1547005383792517 -0.6514527364032653
  0.6679628220644848]
 [1.0 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387 0.4215282412021129
  0.5262737385962607]
 [1.0 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387 0.7104077351727917
  -2.0241297638317715]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.1547005383792517 -0.8165267329579389
  0.5971182803303727]
 [1.0 0.0 1.0 0.0 1.0 0.0 -0.8660254037844387 0.09138024809276578
  -0.6072389291495313]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.1547005

In [32]:
#Feature Scaling on age

In [33]:
X_train[:, 0:1] = sc.fit_transform(X_train[:, 0:1])
X_test[:, 0:1] = sc.fit_transform(X_test[:, 0:1])

In [34]:
print(X_train)

[[-0.9649012813540154 1.0 0.0 1.0 1.0 0.0 -0.4944132324730441
  1.6605950326521113 -0.9941858494300264]
 [-0.9649012813540154 1.0 1.0 0.0 0.0 1.0 -0.4944132324730441
  -0.5372483818439074 0.957435414508189]
 [-0.9649012813540154 1.0 1.0 0.0 1.0 0.0 -0.4944132324730441
  1.1865503746235584 -0.9012515035282067]
 [1.0363754503432017 0.0 1.0 0.0 1.0 0.0 -0.4944132324730441
  -0.23558359946210097 0.957435414508189]
 [-0.9649012813540154 1.0 0.0 1.0 1.0 0.0 -0.4944132324730441
  1.1434554057118715 -0.6224484658227473]
 [-0.9649012813540154 1.0 0.0 1.0 1.0 0.0 -0.4944132324730441
  0.6263157787716319 -1.2729888871354857]
 [1.0363754503432017 0.0 1.0 0.0 0.0 1.0 -0.4944132324730441
  -1.0112930398724607 0.957435414508189]
 [-0.9649012813540154 1.0 1.0 0.0 0.0 1.0 -0.4944132324730441
  0.022986214008018896 1.0503697604100088]
 [1.0363754503432017 0.0 1.0 0.0 1.0 0.0 -0.4944132324730441
  0.45393590312488535 -1.0871201953318463]
 [1.0363754503432017 0.0 0.0 1.0 0.0 1.0 -0.4944132324730441
  -0.1

In [35]:
print(X_test)

[[-2.449489742783178 1.0 1.0 0.0 0.0 0.0 1.1547005383792517
  -0.4451102407099234 0.17205102992570073]
 [0.40824829046386313 0.0 1.0 0.0 0.0 0.0 1.1547005383792517
  -1.0641377277899493 0.9513409890009328]
 [0.40824829046386313 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387
  1.3294352222528176 -1.1739952630224273]
 [0.40824829046386313 0.0 1.0 0.0 0.0 1.0 -0.8660254037844387
  -0.9403322303739441 0.7388073637985968]
 [0.40824829046386313 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387
  0.9580187300048021 -1.1031507212883154]
 [0.40824829046386313 0.0 1.0 0.0 0.0 0.0 1.1547005383792517
  -0.32130474329391817 1.0930300724691568]
 [0.40824829046386313 0.0 1.0 0.0 0.0 0.0 1.1547005383792517
  -0.6514527364032653 0.6679628220644848]
 [0.40824829046386313 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387
  0.4215282412021129 0.5262737385962607]
 [0.40824829046386313 0.0 0.0 1.0 1.0 0.0 -0.8660254037844387
  0.7104077351727917 -2.0241297638317715]
 [0.40824829046386313 0.0 1.0 0.0 0.0 0.0 1.1547005383792517
  -0.81

# **Predection Phase**

### Importing the libraries

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix

### Initialize the model

In [37]:
model = RandomForestClassifier(random_state=42, n_estimators=100)

### Train the model

In [38]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

### Predict on test data

In [39]:
y_pred = model.predict(X_test)

### Evaluate the model

In [40]:
print("Model Performance Metrics:")
print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Model Performance Metrics:
Accuracy: 100.00%

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14



### Confusion Matrix

In [41]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[9 0]
 [0 5]]
